### PR TITLE
WIP: Feature/balance deltas with txs

### PR DESCRIPTION
**Pull request by carolinaf86**
Refactors balanceDeltas query to also return an array of associated txs. Return type is now as follows:
{
items: [Transfer]!
hasMore: Boolean!
txs: [Transaction]
} 

- The "txs" array may be empty if all deltas found are block-related e.g. MINER_FEE or BLOCK_REWARD. 
- If there are multiple deltas related to the same tx, the tx is only returned once.

### CODE REVIEW

**Comment by gsiuniak** [comment]
Looks good. 

The only problem I see at the moment is that the limit results are applied before filtering out txs related to the same transfer results. Not sure there is a way around this? There won't be missing or duplicate results, but the number of items returns for a given offset/limit page is inconsistent because of this.

After talking with Brian, I still feel like the balanceDelta Transfer objects are a better way to represent what we want to display. I think they will come around on the App side.

**Comment by carolinaf86** [comment]
@gsiuniak, yeah hopefully we can convince them this is the best way forward. 

I was giving some thought to paging by tx instead of balance delta though. It would certainly be possible to gather up all deltas for a single tx and count them as "one", and keep asking for more from the DB until we had _n_ txs worth of transfers. However, I can already see a couple of problems with this:

1. There can be A LOT of balance deltas per tx, so one page of txs of balance deltas could be huge. This could mean having to perform many operations on the DB per api query which would be really bad for query performance.
 
2. Some balance deltas are not related to a tx at all, such as miner fees or block rewards. Because of this, these can only be associated with a block and could potentially "get lost" in a page of txs of balances deltas, or at least it's not clear how these should be returned in that case.

**Comment by aldoborrero** [comment]
@carolinaf86 this PR seems to me deprecated, right? If yes, can you close it?

**Comment by carolinaf86** [comment]
> @carolinaf86 this PR seems to me deprecated, right? If yes, can you close it?

Yes, it's deprecated. It can easily be re-implemented if it's needed again in future. Closing,

**Pull request closed without merging**
