### PR TITLE
Fix/notice new block

### PR DESCRIPTION
**Pull request by olgakup**
This pr adds count for number of new blocks/txs/uncles

### CODE REVIEW

**Comment by olgakup** [comment]
hm... not sure how first 2 commits got here, they are from a different pr

**Comment by olgakup** [comment]
@aldoborrero This is ready for review

**Comment by aldoborrero** [comment]
@olgakup you're including work from the PR refactor for the formatting number. As we want to keep separate features from one PR and the other I propose two possible solutions:

1. Delete this PR and just create another one with the specified commit change (not including the other ones)
2. Use git fu and remove from history commits: 984e001, c82fbe9, 85a17c0

**Comment by olgakup** [comment]
@aldoborrero, I deleted those commits.

**Comment by olgakup** [comment]
@aldoborrero can you please double check commit:[ 8fe01e174947b34da772774e6c8f5c690be3e129](https://github.com/EthVM/EthVM/pull/723/commits/8fe01e174947b34da772774e6c8f5c690be3e129)  originally it was not returning the total number of transactions.

**Pull request merged**
