### PR TITLE
WIP: fix(no tokens message): updated string

### PR DESCRIPTION
**Pull request by olgakup**
Still need mainnet link to include in the message

### CODE REVIEW

**Comment by aldoborrero** [comment]
> You are viewing Ropsten testnet which has no tokens of actual monetary value. To view token values please switch to the Ethereum mainnet.

We have here two options:
-  A more generic message something like: This network doesn't have any tokens of actual monetary value.
- Or leave the message as is. The link will be: https://ethvm.com (the production one)

**Comment by olgakup** [comment]
@aldoborrero its better for user experience to provide  a link

**Comment by aldoborrero** [comment]
@olgakup I believe that this PR is deprecated as it has been addressed recently. Can you double check and close if appropriate?

**Comment by olgakup** [comment]
Yes this has been deprecated, closing it!

**Pull request closed without merging**
