### PR TITLE
WIP: Feature/address txs filters and sorting

### PR DESCRIPTION
**Pull request by carolinaf86**
This is a WIP - so far API only has been updated to for new functionality on PageDetailsAddress.vue transactions table: 
- sorting by "timestamp", "value", "fee", "successful", "to" and "from", (asc or desc)
- filtering by "searchHash" which can be a counterpart address or a tx hash

### CODE REVIEW

**Comment by aldoborrero** [comment]
@carolinaf86 and @olgakup does this feature changes too much the api or the front-end? Maybe altough is a feature for post beta, we can include it right away

**Comment by aldoborrero** [comment]
@carolinaf86 and @olgakup does this feature changes too much the api or the front-end? Maybe although is a feature for post beta, we can include it right away

**Comment by aldoborrero** [comment]
@carolinaf86 and @olgakup does this feature changes too much the api or the front-end? Maybe although is a feature for post beta, we can include it right away

**Comment by carolinaf86** [comment]
@aldoborrero, there are actually some quite big changes here - including to processing and db. So maybe it's better to wait for post-beta?

**Comment by aldoborrero** [comment]
@carolinaf86 makes sense then to wait. Let's keep the PR updated with latest develop just to avoid larger merge issues down the road!

**Comment by carolinaf86** [comment]
@aldoborrero the idea is to merge all these post-beta features into one branch which I'm trying to keep updated with develop (feature/post-beta-features). That way we only have to do it in one place.

**Comment by olgakup** [comment]
@carolinaf86, after the merge there are a lot of api errors. Front end is not working can you take a look at it?

**Comment by carolinaf86** [comment]
@olgakup I updated the dataset dump so the API errors should be gone and the explorer has data if you rebuild. Let's have a call later and we can go through how to identify when errors in the API are caused by the incorrect dataset, so you make use of your new super computer and re-process the data ;)

**Pull request closed without merging**
